#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : kdialog
Version  : 18.12.3
Release  : 5
URL      : https://download.kde.org/stable/applications/18.12.3/src/kdialog-18.12.3.tar.xz
Source0  : https://download.kde.org/stable/applications/18.12.3/src/kdialog-18.12.3.tar.xz
Source99 : https://download.kde.org/stable/applications/18.12.3/src/kdialog-18.12.3.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.3 GPL-2.0
Requires: kdialog-bin = %{version}-%{release}
Requires: kdialog-data = %{version}-%{release}
Requires: kdialog-license = %{version}-%{release}
Requires: kdialog-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev

%description
kdialog allows you to display dialog boxes from shell scripts.
The syntax is very much inspired from the "dialog" command
(which shows text mode dialogs).

%package bin
Summary: bin components for the kdialog package.
Group: Binaries
Requires: kdialog-data = %{version}-%{release}
Requires: kdialog-license = %{version}-%{release}

%description bin
bin components for the kdialog package.


%package data
Summary: data components for the kdialog package.
Group: Data

%description data
data components for the kdialog package.


%package license
Summary: license components for the kdialog package.
Group: Default

%description license
license components for the kdialog package.


%package locales
Summary: locales components for the kdialog package.
Group: Default

%description locales
locales components for the kdialog package.


%prep
%setup -q -n kdialog-18.12.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551996702
mkdir -p clr-build
pushd clr-build
export LDFLAGS="${LDFLAGS} -fno-lto"
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1551996702
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kdialog
cp COPYING %{buildroot}/usr/share/package-licenses/kdialog/COPYING
cp COPYING.DOC %{buildroot}/usr/share/package-licenses/kdialog/COPYING.DOC
pushd clr-build
%make_install
popd
%find_lang kdialog

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kdialog
/usr/bin/kdialog_progress_helper

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/interfaces/org.kde.kdialog.ProgressDialog.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kdialog/COPYING
/usr/share/package-licenses/kdialog/COPYING.DOC

%files locales -f kdialog.lang
%defattr(-,root,root,-)

